apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: ko://github.com/retocode/knative-multicontainer-probing/test-server
          env:
            - name: INITIALLY_DOWN
              value: "true"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
  progressDeadlineSeconds: 10
