apiVersion: v1
kind: Pod
metadata:
  annotations:
    autoscaling.knative.dev/min-scale: "1"
    serving.knative.dev/creator: system:admin
  creationTimestamp: "2024-02-07T09:10:51Z"
  generateName: test-probe-00001-deployment-6bc844f7cc-
  labels:
    app: test-probe-00001
    pod-template-hash: 6bc844f7cc
    service.istio.io/canonical-name: test-probe
    service.istio.io/canonical-revision: test-probe-00001
    serving.knative.dev/configuration: test-probe
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: fb422af9-a55d-4c8b-80b6-1806e7a40426
    serving.knative.dev/revision: test-probe-00001
    serving.knative.dev/revisionUID: d17a62b1-1ffb-48b4-a01e-757ea73d90c1
    serving.knative.dev/service: test-probe
    serving.knative.dev/serviceUID: 5e9ee1e9-55ca-4f28-932b-11e60f7ddc95
  name: test-probe-00001-deployment-6bc844f7cc-25mbs
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: test-probe-00001-deployment-6bc844f7cc
    uid: cd7932b6-8c31-4ff6-b637-666f49dcb1cc
  resourceVersion: "2810404"
  uid: a416ae66-a9c1-4509-85ff-95e9ed10a00f
spec:
  containers:
  - env:
    - name: PORT
      value: "8080"
    - name: K_REVISION
      value: test-probe-00001
    - name: K_CONFIGURATION
      value: test-probe
    - name: K_SERVICE
      value: test-probe
    image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:6e75008c345f398da10018549431a019a589c8d22b0935120f658f1a4c0a8ae1
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        httpGet:
          path: /wait-for-drain
          port: 8022
          scheme: HTTP
    name: first-container
    ports:
    - containerPort: 8080
      name: user-port
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xnz86
      readOnly: true
  - env:
    - name: SERVING_NAMESPACE
      value: default
    - name: SERVING_SERVICE
      value: test-probe
    - name: SERVING_CONFIGURATION
      value: test-probe
    - name: SERVING_REVISION
      value: test-probe-00001
    - name: QUEUE_SERVING_PORT
      value: "8012"
    - name: QUEUE_SERVING_TLS_PORT
      value: "8112"
    - name: CONTAINER_CONCURRENCY
      value: "0"
    - name: REVISION_TIMEOUT_SECONDS
      value: "300"
    - name: REVISION_RESPONSE_START_TIMEOUT_SECONDS
      value: "0"
    - name: REVISION_IDLE_TIMEOUT_SECONDS
      value: "0"
    - name: SERVING_POD
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: SERVING_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVING_LOGGING_CONFIG
    - name: SERVING_LOGGING_LEVEL
      value: debug
    - name: SERVING_REQUEST_LOG_TEMPLATE
      value: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl":
        "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}",
        "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent":
        "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp":
        "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s",
        "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
    - name: SERVING_ENABLE_REQUEST_LOG
      value: "true"
    - name: SERVING_REQUEST_METRICS_BACKEND
      value: prometheus
    - name: SERVING_REQUEST_METRICS_REPORTING_PERIOD_SECONDS
      value: "5"
    - name: TRACING_CONFIG_BACKEND
      value: none
    - name: TRACING_CONFIG_ZIPKIN_ENDPOINT
    - name: TRACING_CONFIG_DEBUG
      value: "false"
    - name: TRACING_CONFIG_SAMPLE_RATE
      value: "0.1"
    - name: USER_PORT
      value: "8080"
    - name: SYSTEM_NAMESPACE
      value: knative-serving
    - name: METRICS_DOMAIN
      value: knative.dev/internal/serving
    - name: SERVING_READINESS_PROBE
      value: '{"httpGet":{"path":"/ready","port":8080,"host":"127.0.0.1","scheme":"HTTP","httpHeaders":[{"name":"K-Kubelet-Probe","value":"queue"}]},"successThreshold":1}'
    - name: ENABLE_PROFILING
      value: "false"
    - name: SERVING_ENABLE_PROBE_REQUEST_LOG
      value: "true"
    - name: METRICS_COLLECTOR_ADDRESS
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: ENABLE_HTTP2_AUTO_DETECTION
      value: "false"
    - name: ENABLE_HTTP_FULL_DUPLEX
      value: "false"
    - name: ROOT_CA
    image: ko.local/queue-39be6f1d08a095bd076a71d288d295b6:ef280b38efe99527fd9ff74098f03adba334d2bd767bd44622643e8e9150e027
    imagePullPolicy: IfNotPresent
    name: queue-proxy
    ports:
    - containerPort: 8022
      name: http-queueadm
      protocol: TCP
    - containerPort: 9090
      name: http-autometric
      protocol: TCP
    - containerPort: 9091
      name: http-usermetric
      protocol: TCP
    - containerPort: 8012
      name: queue-port
      protocol: TCP
    - containerPort: 8112
      name: https-port
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        httpHeaders:
        - name: K-Network-Probe
          value: queue
        path: /
        port: 8012
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 25m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/knative/certs
      name: server-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xnz86
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  nodeName: colima
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 300
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: server-certs
    secret:
      defaultMode: 420
      secretName: serving-certs
  - name: kube-api-access-xnz86
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-07T09:10:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-07T09:10:51Z"
    message: 'containers with unready status: [queue-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-07T09:10:51Z"
    message: 'containers with unready status: [queue-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-07T09:10:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://dafada2d4da2c82a1d7228df6274b496d230240266d426142c5c1ae457830dc5
    image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:6e75008c345f398da10018549431a019a589c8d22b0935120f658f1a4c0a8ae1
    imageID: docker://sha256:d2c6e8c30438931e5e3289ad053ea105a984bef8e8a95d70d9032364807750f3
    lastState: {}
    name: first-container
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-07T09:10:52Z"
  - containerID: docker://e38aef31e1e484e1c78c2aebc12e6497f385baa1e193dda89161634f74bc2a9c
    image: ko.local/queue-39be6f1d08a095bd076a71d288d295b6:ef280b38efe99527fd9ff74098f03adba334d2bd767bd44622643e8e9150e027
    imageID: docker://sha256:9bd802e1570327b50c94682ea95068a1c76cbc9c891708838cdf8d6460d0fcc4
    lastState: {}
    name: queue-proxy
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-07T09:10:52Z"
  hostIP: 192.168.5.1
  phase: Running
  podIP: 10.42.0.189
  podIPs:
  - ip: 10.42.0.189
  qosClass: Burstable
  startTime: "2024-02-07T09:10:51Z"
