apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  annotations:
    autoscaling.knative.dev/min-scale: "1"
    serving.knative.dev/creator: system:admin
    serving.knative.dev/routes: test-probe
    serving.knative.dev/routingStateModified: "2024-02-07T07:55:45Z"
  creationTimestamp: "2024-02-07T07:55:45Z"
  generation: 1
  labels:
    serving.knative.dev/configuration: test-probe
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: 1596f60c-00fe-4da5-b57b-0bf0a6b1e732
    serving.knative.dev/routingState: active
    serving.knative.dev/service: test-probe
    serving.knative.dev/serviceUID: b280cf34-181a-492e-a2bf-f9b7d71aaa8d
  name: test-probe-00001
  namespace: default
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Configuration
    name: test-probe
    uid: 1596f60c-00fe-4da5-b57b-0bf0a6b1e732
  resourceVersion: "2794082"
  uid: 73d21f47-46dd-4dd5-ba60-b0f27b3b834d
spec:
  containerConcurrency: 0
  containers:
  - image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:6e75008c345f398da10018549431a019a589c8d22b0935120f658f1a4c0a8ae1
    name: first-container
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      successThreshold: 1
    resources: {}
  enableServiceLinks: false
  timeoutSeconds: 300
status:
  actualReplicas: 0
  conditions:
  - lastTransitionTime: "2024-02-07T07:55:45Z"
    message: Requests to the target are being buffered as resources are provisioned.
    reason: Queued
    severity: Info
    status: Unknown
    type: Active
  - lastTransitionTime: "2024-02-07T07:55:45Z"
    status: Unknown
    type: ContainerHealthy
  - lastTransitionTime: "2024-02-07T07:55:45Z"
    status: Unknown
    type: Ready
  - lastTransitionTime: "2024-02-07T07:55:45Z"
    status: "True"
    type: ResourcesAvailable
  containerStatuses:
  - name: first-container
  desiredReplicas: 1
  observedGeneration: 1
