apiVersion: v1
kind: Pod
metadata:
  annotations:
    autoscaling.knative.dev/min-scale: "1"
    serving.knative.dev/creator: system:admin
  creationTimestamp: "2024-01-31T10:01:27Z"
  generateName: runtime-00001-deployment-75884dc4b9-
  labels:
    app: runtime-00001
    pod-template-hash: 75884dc4b9
    serving.knative.dev/configuration: runtime
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: 03ab3dcc-250f-46c5-96ec-cf8a0f102d68
    serving.knative.dev/revision: runtime-00001
    serving.knative.dev/revisionUID: c9eac4e6-8d48-42d0-8460-76860cfae33c
    serving.knative.dev/service: runtime
    serving.knative.dev/serviceUID: a17dc5ff-2c5a-47da-a92f-a59a685ac7b1
  name: runtime-00001-deployment-75884dc4b9-4phq7
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: runtime-00001-deployment-75884dc4b9
      uid: 64c5203e-cca6-4116-a832-59b32fd980b5
  resourceVersion: "2589608"
  uid: 4cd80613-4055-446f-95d8-a79f4f467614
spec:
  containers:
    - env:
        - name: PORT
          value: "8080"
        - name: K_REVISION
          value: runtime-00001
        - name: K_CONFIGURATION
          value: runtime
        - name: K_SERVICE
          value: runtime
      image: quay.io/rlehmann/runtime@sha256:291e040a8331bfa83968944c4f9cee586923e816c9833e0283d287300498ffa4
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          httpGet:
            path: /wait-for-drain
            port: 8022
            scheme: HTTP
      name: first-container
      ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-njgvv
          readOnly: true
    - env:
        - name: PORT
          value: "8080"
        - name: K_REVISION
          value: runtime-00001
        - name: K_CONFIGURATION
          value: runtime
        - name: K_SERVICE
          value: runtime
      image: quay.io/rlehmann/runtime@sha256:291e040a8331bfa83968944c4f9cee586923e816c9833e0283d287300498ffa4
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          httpGet:
            path: /wait-for-drain
            port: 8022
            scheme: HTTP
      name: second-container
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-njgvv
          readOnly: true
    - env:
        - name: SERVING_NAMESPACE
          value: default
        - name: SERVING_SERVICE
          value: runtime
        - name: SERVING_CONFIGURATION
          value: runtime
        - name: SERVING_REVISION
          value: runtime-00001
        - name: QUEUE_SERVING_PORT
          value: "8012"
        - name: QUEUE_SERVING_TLS_PORT
          value: "8112"
        - name: CONTAINER_CONCURRENCY
          value: "0"
        - name: REVISION_TIMEOUT_SECONDS
          value: "300"
        - name: REVISION_RESPONSE_START_TIMEOUT_SECONDS
          value: "0"
        - name: REVISION_IDLE_TIMEOUT_SECONDS
          value: "0"
        - name: SERVING_POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SERVING_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVING_LOGGING_CONFIG
        - name: SERVING_LOGGING_LEVEL
          value: debug
        - name: SERVING_REQUEST_LOG_TEMPLATE
          value: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl":
        "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}",
        "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent":
        "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp":
        "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s",
        "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
        - name: SERVING_ENABLE_REQUEST_LOG
          value: "true"
        - name: SERVING_REQUEST_METRICS_BACKEND
          value: prometheus
        - name: SERVING_REQUEST_METRICS_REPORTING_PERIOD_SECONDS
          value: "5"
        - name: TRACING_CONFIG_BACKEND
          value: none
        - name: TRACING_CONFIG_ZIPKIN_ENDPOINT
        - name: TRACING_CONFIG_DEBUG
          value: "false"
        - name: TRACING_CONFIG_SAMPLE_RATE
          value: "0.1"
        - name: USER_PORT
          value: "8080"
        - name: SYSTEM_NAMESPACE
          value: knative-serving
        - name: METRICS_DOMAIN
          value: knative.dev/internal/serving
        - name: SERVING_READINESS_PROBE
          value: '[{"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}]'
        - name: ENABLE_PROFILING
          value: "false"
        - name: SERVING_ENABLE_PROBE_REQUEST_LOG
          value: "true"
        - name: METRICS_COLLECTOR_ADDRESS
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ENABLE_HTTP2_AUTO_DETECTION
          value: "false"
        - name: ENABLE_HTTP_FULL_DUPLEX
          value: "false"
        - name: ROOT_CA
        - name: ENABLE_MULTI_CONTAINER_PROBES
          value: "true"
      image: ko.local/queue-39be6f1d08a095bd076a71d288d295b6:905d2c3c2101823312f37dd584f9cb1bdabb48e036e5bdd5f1e861f630d18582
      imagePullPolicy: IfNotPresent
      name: queue-proxy
      ports:
        - containerPort: 8022
          name: http-queueadm
          protocol: TCP
        - containerPort: 9090
          name: http-autometric
          protocol: TCP
        - containerPort: 9091
          name: http-usermetric
          protocol: TCP
        - containerPort: 8012
          name: queue-port
          protocol: TCP
        - containerPort: 8112
          name: https-port
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          httpHeaders:
            - name: K-Network-Probe
              value: queue
          path: /
          port: 8012
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        requests:
          cpu: 25m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-njgvv
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  nodeName: colima
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 300
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-njgvv
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:01:27Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:01:28Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:01:28Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:01:27Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://dc570e584478edbee0313d2920009e95cfc86147be295684a756a257ab14ae19
      image: sha256:156195ab811a284230a10cac14af5dc59ce69f132c856de84668e51ecd5fb0d2
      imageID: docker-pullable://quay.io/rlehmann/runtime@sha256:291e040a8331bfa83968944c4f9cee586923e816c9833e0283d287300498ffa4
      lastState: {}
      name: first-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-31T10:01:28Z"
    - containerID: docker://de7653290bb30e97f14fbed4468f4002f554c4128faa7a515efa6985f6998684
      image: ko.local/queue-39be6f1d08a095bd076a71d288d295b6:905d2c3c2101823312f37dd584f9cb1bdabb48e036e5bdd5f1e861f630d18582
      imageID: docker://sha256:45c54e591bbf4057ade28726532ac2b05b843705c3a29789af81617b77f798a9
      lastState: {}
      name: queue-proxy
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-31T10:01:28Z"
    - containerID: docker://4b910ab0b6c6e3b84c1800c28b42536048b672c6496b3bae372ee702a85b361f
      image: sha256:156195ab811a284230a10cac14af5dc59ce69f132c856de84668e51ecd5fb0d2
      imageID: docker-pullable://quay.io/rlehmann/runtime@sha256:291e040a8331bfa83968944c4f9cee586923e816c9833e0283d287300498ffa4
      lastState: {}
      name: second-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-31T10:01:28Z"
  hostIP: 192.168.5.1
  phase: Running
  podIP: 10.42.0.99
  podIPs:
    - ip: 10.42.0.99
  qosClass: Burstable
  startTime: "2024-01-31T10:01:27Z"
