apiVersion: v1
kind: Pod
metadata:
  annotations:
    autoscaling.knative.dev/min-scale: "1"
    serving.knative.dev/creator: system:admin
  creationTimestamp: "2024-01-31T10:39:39Z"
  generateName: test-probe-00001-deployment-7cdfcbc98d-
  labels:
    app: test-probe-00001
    pod-template-hash: 7cdfcbc98d
    serving.knative.dev/configuration: test-probe
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: 9d02c0e5-96eb-42c2-94ef-2503d647e294
    serving.knative.dev/revision: test-probe-00001
    serving.knative.dev/revisionUID: 73790684-de24-4875-8f4b-5cd20555e55c
    serving.knative.dev/service: test-probe
    serving.knative.dev/serviceUID: fd86a7f4-8c40-4fc6-8df3-9adab2abbd69
  name: test-probe-00001-deployment-7cdfcbc98d-mdbc4
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: test-probe-00001-deployment-7cdfcbc98d
      uid: 4a8637ed-ba44-4609-9429-ac9db0ebd33a
  resourceVersion: "2595528"
  uid: 1bf12283-4ea3-42da-8c1c-65c5cb881797
spec:
  containers:
    - env:
        - name: PORT
          value: "8080"
        - name: K_REVISION
          value: test-probe-00001
        - name: K_CONFIGURATION
          value: test-probe
        - name: K_SERVICE
          value: test-probe
      image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:17310f7080d853b6689efb21026c934296c7186611995af34a07cb698d1dcc8f
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          httpGet:
            path: /wait-for-drain
            port: 8022
            scheme: HTTP
      livenessProbe:
        failureThreshold: 3
        httpGet:
          httpHeaders:
            - name: K-Kubelet-Probe
              value: queue
          path: /live
          port: 8080
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: first-container
      ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-kklgh
          readOnly: true
    - env:
        - name: PORT
          value: "8090"
        - name: K_REVISION
          value: test-probe-00001
        - name: K_CONFIGURATION
          value: test-probe
        - name: K_SERVICE
          value: test-probe
      image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:17310f7080d853b6689efb21026c934296c7186611995af34a07cb698d1dcc8f
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          httpGet:
            path: /wait-for-drain
            port: 8022
            scheme: HTTP
      livenessProbe:
        failureThreshold: 3
        httpGet:
          httpHeaders:
            - name: K-Kubelet-Probe
              value: queue
          path: /live
          port: 8090
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: second-container
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-kklgh
          readOnly: true
    - env:
        - name: SERVING_NAMESPACE
          value: default
        - name: SERVING_SERVICE
          value: test-probe
        - name: SERVING_CONFIGURATION
          value: test-probe
        - name: SERVING_REVISION
          value: test-probe-00001
        - name: QUEUE_SERVING_PORT
          value: "8012"
        - name: QUEUE_SERVING_TLS_PORT
          value: "8112"
        - name: CONTAINER_CONCURRENCY
          value: "0"
        - name: REVISION_TIMEOUT_SECONDS
          value: "300"
        - name: REVISION_RESPONSE_START_TIMEOUT_SECONDS
          value: "0"
        - name: REVISION_IDLE_TIMEOUT_SECONDS
          value: "0"
        - name: SERVING_POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SERVING_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVING_LOGGING_CONFIG
        - name: SERVING_LOGGING_LEVEL
          value: debug
        - name: SERVING_REQUEST_LOG_TEMPLATE
          value: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl":
        "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}",
        "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent":
        "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp":
        "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s",
        "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
        - name: SERVING_ENABLE_REQUEST_LOG
          value: "true"
        - name: SERVING_REQUEST_METRICS_BACKEND
          value: prometheus
        - name: SERVING_REQUEST_METRICS_REPORTING_PERIOD_SECONDS
          value: "5"
        - name: TRACING_CONFIG_BACKEND
          value: none
        - name: TRACING_CONFIG_ZIPKIN_ENDPOINT
        - name: TRACING_CONFIG_DEBUG
          value: "false"
        - name: TRACING_CONFIG_SAMPLE_RATE
          value: "0.1"
        - name: USER_PORT
          value: "8080"
        - name: SYSTEM_NAMESPACE
          value: knative-serving
        - name: METRICS_DOMAIN
          value: knative.dev/internal/serving
        - name: SERVING_READINESS_PROBE
          value: '[{"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}]'
        - name: ENABLE_PROFILING
          value: "false"
        - name: SERVING_ENABLE_PROBE_REQUEST_LOG
          value: "true"
        - name: METRICS_COLLECTOR_ADDRESS
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ENABLE_HTTP2_AUTO_DETECTION
          value: "false"
        - name: ENABLE_HTTP_FULL_DUPLEX
          value: "false"
        - name: ROOT_CA
        - name: ENABLE_MULTI_CONTAINER_PROBES
          value: "true"
      image: ko.local/queue-39be6f1d08a095bd076a71d288d295b6:905d2c3c2101823312f37dd584f9cb1bdabb48e036e5bdd5f1e861f630d18582
      imagePullPolicy: IfNotPresent
      name: queue-proxy
      ports:
        - containerPort: 8022
          name: http-queueadm
          protocol: TCP
        - containerPort: 9090
          name: http-autometric
          protocol: TCP
        - containerPort: 9091
          name: http-usermetric
          protocol: TCP
        - containerPort: 8012
          name: queue-port
          protocol: TCP
        - containerPort: 8112
          name: https-port
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          httpHeaders:
            - name: K-Network-Probe
              value: queue
          path: /
          port: 8012
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        requests:
          cpu: 25m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-kklgh
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  nodeName: colima
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 300
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-kklgh
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:39:39Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:39:39Z"
      message: 'containers with unready status: [queue-proxy]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:39:39Z"
      message: 'containers with unready status: [queue-proxy]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-31T10:39:39Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://d44e2b2a91c6a4e99cc9c21f3969e382f5299801eb21ae8c5372cde351e9ba40
      image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:17310f7080d853b6689efb21026c934296c7186611995af34a07cb698d1dcc8f
      imageID: docker://sha256:ce205271bb0c6f65cd1fc5cb0f11d85c08340f58bd31eb6d3e5d12d2e2d5365c
      lastState: {}
      name: first-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-31T10:39:39Z"
    - containerID: docker://00398e2b38b50e2d53a9d5def6864a67924cd517420f38e5c0a8833a367f58bf
      image: ko.local/queue-39be6f1d08a095bd076a71d288d295b6:905d2c3c2101823312f37dd584f9cb1bdabb48e036e5bdd5f1e861f630d18582
      imageID: docker://sha256:45c54e591bbf4057ade28726532ac2b05b843705c3a29789af81617b77f798a9
      lastState: {}
      name: queue-proxy
      ready: false
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-31T10:39:40Z"
    - containerID: docker://0aea75cd897c25ce15b9b0e8b7a9aa0b80490445c74f1b457fc72de8e327becc
      image: ko.local/test-server-4e77235dce690edd6b45122a823a55c7:17310f7080d853b6689efb21026c934296c7186611995af34a07cb698d1dcc8f
      imageID: docker://sha256:ce205271bb0c6f65cd1fc5cb0f11d85c08340f58bd31eb6d3e5d12d2e2d5365c
      lastState: {}
      name: second-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-31T10:39:39Z"
  hostIP: 192.168.5.1
  phase: Running
  podIP: 10.42.0.110
  podIPs:
    - ip: 10.42.0.110
  qosClass: Burstable
  startTime: "2024-01-31T10:39:39Z"
